name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t cake-frontend ./frontend

    - name: Run Docker Container
      run: |
        docker run -d -p 3000:3000 --name cake-frontend cake-frontend
